version: '3'
services:
  crimson-backend:
    build: crimson-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
  crimson-portal:
    build: crimson-portal
    ports:
      - "3000:3000"
    links:
     - crimson-backend
    environment:
      - PORT=3000
      - BACKEND_HOST=crimson-backend
      - BACKEND_PORT=8080
      - POSTBOX_URL=http://${CRIMSON_SERVER:-localhost}:3001
      - LETTER_URL=http://${CRIMSON_SERVER:-localhost}:3002
      - DAMAGE_URL=http://${CRIMSON_SERVER:-localhost}:3003
  crimson-damage:
    build: crimson-damage
    ports:
      - "3003:3003"
    links:
     - crimson-backend
    environment:
      - PORT=3003
      - BACKEND_HOST=crimson-backend
      - BACKEND_PORT=8080
      - POSTBOX_URL=http://${CRIMSON_SERVER:-localhost}:3001
      - ROCA_URL=http://${CRIMSON_SERVER:-localhost}:3000
  crimson-postbox:
    build: crimson-postbox
    ports:
      - "3001:3001"
    links:
     - crimson-backend
    environment:
      - SERVER_PORT=3001
      - lasRestServiceUrl=http://crimson-backend:8080
      - lasRocaUrl=http://${CRIMSON_SERVER:-localhost}:3000
  crimson-letter:
    build: crimson-letter
    ports:
      - "3002:3002"
    links:
     - crimson-backend
    environment:
      - PORT=3002
      - BACKEND_HOST=crimson-backend
      - BACKEND_PORT=8080
      - POSTBOX_URL=http://${CRIMSON_SERVER:-localhost}:3001
